### ISSUE TITLE
Image policy

### ISSUE THREAD

**Issue by outscale-vbr** [outscale/cluster-api-provider-outscale#116]
### Explain problem to solve

We will delete old image every 6 months.
(In order to keep 3 version of kubernetes)

### Describe the solution you would like

Options 1:
Patch this projet to not use autoscaling
https://github.com/bonclay7/aws-amicleaner
And integrate to a github ci pipeline

Options 2:
Create a script with osc-sdk-python to delete image that is older than 6 months.
Garder la dernière version au sein d'une majeur au cas où .
And integrate to a github ci pipeline

### Additional context

None

### Environment

```markdown
- Kubernetes version: (use `kubectl version`): v1.22.5-rancher1-1
- OS (e.g. from `/etc/os-release`): CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`): 3.10.0-1160.15.2.el7.x86_64
- cluster-api-provider-outscale version: v1.1.3
- cluster-api version: current
- Install tools: calico, ingress-nginx, osc-ccm
- Kubernetes Distribution: rke
- Kubernetes Distribution version: v1.3.4
```

**Comment by outscale-hmi** [comment]
Done and merged
