### ISSUE TITLE
[Bug]: mismatch with providerID set by cloud-provider-osc

### ISSUE THREAD

**Issue by azert9** [outscale/cluster-api-provider-outscale#259]
### What happened

The providerID generated by this provider follows the format `aws://placement/vm-id`, whereas the Outscale CCM uses `aws:///placement/vm-id`. This creates an incompatibility between the two, as cluster api expects an exact match.

This is not an issue in your kubeadm-based examples, as the kubeadm provider allows building a custom providerID using metadata. However, not all bootstrap providers have this feature (e.g. Talos). 

### Step to reproduce

* Provision a cluster using cluster api with this infra provider, without setting providerIDs explicitly.
* Install cloud-provider-osc in the cluster.
* Watch the state of the "Machine" cluster-api resource. It stays stuck at "Provisioned", and the "NodeHealthy" condition stays false.

If you repeat the steps above but without the CCM, and you set the providerID manually to match the aws:// format, the machines eventually become ready.

### Expected to happen

The providerIDs set in nodes of the workload cluster should match the providerIDs set on OscMachine resources.

### Add anything

The [aws cluster-api provider](https://github.com/kubernetes-sigs/cluster-api-provider-aws) does not have this issue because the three-slashes format "aws:///" is used everywhere, so maybe the easiest fix would be to align to this convention.

What do you think?

### cluster-api output

I did not find any relevant log line, however by doing a little debugging I found [this line](https://github.com/kubernetes-sigs/cluster-api/blob/46412f0a4ea65d8f02478d2ad09ce12925485f56/internal/controllers/machine/machine_controller_noderef.go#L69C22-L69C22) which returns an error saying "cannot find node with matching ProviderID".

### Environment

```markdown
- Kubernetes version: v1.27.4
- OS (e.g. from `/etc/os-release`): Talos v1.4.8
- Kernel (e.g. `uname -a`):
- cluster-api-provider-outscale version: v0.2.2
- cluster-api version: v1.5.0
- Install tools: local kind cluster
- Kubernetes Distribution: Talos
- Kubernetes Diestribution version: v1.4.8
```

**Comment by outscale-vbr** [comment]
Hi @azert9 ,
Thanks for reaching us.
Migrate providerId from aws:// to aws:/// is a good idea to solve your problem so that ccm will initialize your cluster ProviderID and will be compatible with cluster-api ProviderID.
Because it is a change of behavior of cluster-api, we will add a documentation to migrate an existing cluster.

**Comment by outscale-vbr** [comment]
Is it possible to share your config to create a talos cluster (MachineHealthCheck, OscMachineTemplate, MachineDeployment, TalosConfigTemplate, TalosControlPlane, Cluster, OscCluster, ClusterResourceSet ?) without you ak/sk because  we have only  tested with kubeadm bootstrapper ?
