### ISSUE TITLE
[Feature]: enable tinav6 instances

### ISSUE THREAD

**Issue by mickaelicoptere** [outscale/cluster-api-provider-outscale#269]
### Explain problem to solve

Hi,
Our use case needs tinav6 instances for gpu provisionning. I noticed the validation is enabling up to `tinav5` instance types [here](https://github.com/outscale/cluster-api-provider-outscale/blob/4e82d5235ee2da56cbc9b0e1e97fd73138f2161a/api/v1beta1/oscmachine_validation.go#L205).

Will any support for tinav6 instances be implemented in outscale capi provider ?

Thanks.
Best regards,

Mickael

### Describe the solution you would like

I wish to provision tinav6 instances type using the clusterapi.

### Additional context

tinav6 are needed for gpu provisionning on outscale as far as i know

### Environment

```markdown
- Kubernetes version: (use `kubectl version`): v1.28.2
- OS (e.g. from `/etc/os-release`): ubuntu-2204-2204
- Kernel (e.g. `uname -a`):
- cluster-api-provider-outscale version: v0.2.3
- cluster-api version: v1.5.1
- Install tools: calico
- Kubernetes Distribution: kubeadm
- Kubernetes Diestribution version: v1.25.10
```

**Comment by outscale-vbr** [comment]
Hi @mickaelicoptere ,
TinaV6 instance are now available in the latest release (v0.2.4),
Best regards,
Vincent BAER
