### ISSUE TITLE
[Feature]: update cloudgov images

### ISSUE THREAD

**Issue by pierreozoux** [outscale/cluster-api-provider-outscale#281]
### Explain problem to solve

The cloudgov ami are outdated:
https://github.com/outscale/cluster-api-provider-outscale/blob/main/docs/src/topics/omi.md?plain=1#L24-L26

### Describe the solution you would like

I'd like an update.

### Additional context

Thanks for your help!

### Environment

```markdown
.
```

**Comment by outscale-vbr** [comment]
hi @pierreozoux 
New image are now available on cloudgov.
https://cluster-api-outscale.oos-website.eu-west-2.outscale.com/topics/omi.html

**Comment by pierreozoux** [comment]
Basically, if we could have the same VMs as in the regular region, this would be amazing :)

How could I build it myself in the meantime?

Thanks for your help!

**Comment by pierreozoux** [comment]
Est-ce que ce serait possible de copier les images d'un AZ vers cloud gov?

J'ai essayé de les build moi meme avec:
https://github.com/kubernetes-sigs/image-builder/blob/main/images/capi/scripts/ci-outscale-nightly.sh

mais je n'arrive pas à les boot :/
(décris dans ce ticket interne outscale: 372403 )

**Comment by outscale-vbr** [comment]
Hi @pierreozoux,
ubuntu-2204-2004-kubernetes-v1.23.8-2023-02-10 and ubuntu-2004-2004-kubernetes-v1.24.2-2022-10-13are now availabled on cloudgouv-eu-west-1.
Also a new doc are  now available to build omi based on ubuntu with image-builder and packer (https://cluster-api-outscale.oos-website.eu-west-2.outscale.com/developers/release-custom-omi-ubuntu.html).

**Comment by pierreozoux** [comment]
Thanks a lot \o/

I'm testing the update procedure now.
