### ISSUE TITLE
[Bug]:  OSCMachine deployment stuck silently if OscMachineTemplate keyPair not exist

### ISSUE THREAD

**Issue by sebglon** [outscale/cluster-api-provider-outscale#293]
### What happened

OscMachine deployment is stuck without error or warning logs on the operator

### Step to reproduce

create an OscMachineTemplate with a bad KeyPairName;
create an OscMachine that ref the previous OscMachineTemplate

### Expected to happen

We have an error / warning logs on the Operator
And Maybe an error event on the OscMachine resource

### Add anything

-

### cluster-api output

-

### Environment

```markdown
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):
- Kernel (e.g. `uname -a`):
- cluster-api-provider-outscale version:
- cluster-api version: 
- Install tools:
- Kubernetes Distribution:
- Kubernetes Diestribution version:
```

**Comment by outscale-vbr** [comment]
Hi @sebglon ,
Why do you create an oscmachine as oscMachineTemplate will be used witrh machineDeployment/ to create oscmachine with a bad keypair?


**Cluster-Api-Provider-outscale behavior**
You should really create a keypair before.
If you don't create the keypair, a keypair will be created  but you will not have the private keypair.
```
{"ResponseContext":{"RequestId":"0a9bccf0-5d0f-4812-99b9-acd089607154"},"Keypairs":[]}
Debug Returning backoff with params: duration(1), factor(2), steps(20) 
{"level":"Level(-2)","ts":"2024-01-23T17:43:25Z","msg":"Keypair will be created","controller":"oscmachine","controllerGroup":"infrastructure.cluster.x-k8s.io","controllerKind":"OscMachine","OscMachine":{"name":"keypair-test-control-plane-b2sq7","namespace":"default"},"namespace":"default","name":"keypair-test-control-plane-b2sq7","reconcileID":"210b0cdd-d8b4-4e4b-a64c-4b3464fca866","machine":"keypair-test-control-plane-x2md8","keypair":"keypair-test-fake"}
2024/01/23 17:43:25 
POST /api/v1/CreateKeypair HTTP/1.1
Host: api.cloudgouv-eu-west-1.outscale.com
User-Agent: cluster-api-provider-outscale/v0.3.0
Content-Length: 36
Accept: application/json
Authorization: AWS4-HMAC-SHA256 Credential=P44QLYCA8G1WKL0FDNPI/20240123/eu-west-2/oapi/aws4_request, SignedHeaders=accept;content-type;host;x-amz-date, Signature=a1b1a64a295bf3be0b9b71a683fd42db8e1ea3194bcde0572c0da02dce86b325
Content-Type: application/json
X-Amz-Date: 20240123T174325Z
Accept-Encoding: gzip

{"KeypairName":"keypair-test-fake"}
```


**Steps of workaround**
Create an other OscMachineTemplate with bad keypair and an other machineDeployment. You node will be created by you will not have the private keypair.
ANd after you can delete previous OscMachineTemplate and machineDeployment .

But you can have an ssh access with this kubectl plugin (https://github.com/luksa/kubectl-plugins/tree/master)

**Comment by outscale-hmi** [comment]
this issue can be related this this one [https://github.com/outscale/cluster-api-provider-outscale/issues/90]
