### ISSUE TITLE
Be compatible with self hosted cluster (management/workload cluster are on the same cluster)

### ISSUE THREAD

**Issue by outscale-vbr** [outscale/cluster-api-provider-outscale#307]
### Explain problem to solve

If the management and workload cluster are on the same cluster, cluster-api will create the nat.
If you remove the nat, Cluster-api doesn't have access to outscale api. If you recreate yourself, cluster-api will not approve because not the same id.

### Describe the solution you would like

Specify natgateway you want or do not delete nategateway parameters

### Additional context

None

### Environment

None

**Comment by outscale-vbr** [comment]
@pierreozoux

**Comment by pierreozoux** [comment]
Hi,

In zendesk, I explained my issue.
The start of the issue, was an outscale bug, I tear down a test vpc, and it deleted my production nat, now, this tear down functionnality is disabled:
https://docs.outscale.com/en/userguide/Deleting-a-Net.html#_deleting_a_net_and_its_associated_resources

And then, I had a "normal issue", the management cluster is trying to recreate it, but it doesn't have access to cluster API. It is normal, and I don't know a way to fix it.
But, in the end, I could recreate the nat manually, give it the same name, and change the resource in kubernetes to give it the name of the manually recreated nat, and the automation is happy.

So, on my side, there is no bug, I was happy to find a way to make the automation happy again.

Is it clearer? For me you can close it.

Thanks for caring, and have a nice day!
