### ISSUE TITLE
[Feature]: Document a policy example for cluster API

### ISSUE THREAD

**Issue by pierreozoux** [outscale/cluster-api-provider-outscale#388]
### Explain problem to solve

We want to have a tight configuration of EIM policy associated to this controller.

### Describe the solution you would like

We'd like a nice policy json example, like here:
- https://github.com/outscale/cloud-provider-osc/blob/578494e159e8e0f6abd772db22364c4f4f453288/deploy/eim-policy.example.json#L4
- https://github.com/outscale/osc-bsu-csi-driver/blob/3f9d1858b5295546313303e6fe0a2b3b277abaaf/docs/example-eim-policy.json#L4

### Additional context

,

### Environment

```markdown
.
```

**Comment by outscale-hmi** [comment]
Hello, 
We will test it on our end and keep you updated today.

**Comment by pierreozoux** [comment]
Thanks! 

https://github.com/outscale/cluster-api-provider-outscale/commit/7a9f1f89ed345a263598bb79b03add2edca57f76
